Register individual button on login page  rederects to register indiv…
LearnDeepMilwaukee/rea-app pull request #76
Opened 2019-05-09 14:46 UTC by DonalMoloneyMSOE

…idual page

2019-05-09 23:46 UTC, larsonme commented on src/pages/Individuals/individualRegistration.tsx
> +// import {adminToken} from "../../apiKeys.json";
This needs to be uncommented/left as it was on dev

2019-05-09 23:47 UTC, larsonme commented on src/pages/LoginPage.js
> +    handleRegister() {
Change this to 'handleRegister = () => {'
instead of 'handleRegister() {'
This won't access props otherwise(I believe)

2019-05-09 23:48 UTC, larsonme commented on src/pages/LoginPage.js
> +                                        <Button color='blue' fluid type='button' onClick={this.handleRegister()} size='large'>Register</Button>
Make this 'this.handleRegister' aka remove the ().  The () means it is called/evaluated at compile time which is causing a redirect everytime.

2019-05-09 23:49 UTC, larsonme requested changes
This currently doesn't work, just try and click the register button on the login page.  Slack me if you have any questions on my comments/when it's ready for review again/if you need help with the merge conflicts

2019-05-14 14:03 UTC, larsonme approved these changes

2019-05-14 14:19 UTC, StrikeNP approved these changes
When attempting to create a new user the username/email checks don't work. If I enter an existing username "connor" it throws no error, if I enter an unused username e.g. "connord" it does throw an error saying either "   " or "An account with this username already exists". If I continue typing, this message goes away. This is a bug that needs to be fixed, but may not be within the scope of this branch. The register redirect appears to work properly, so I'll TENTATIVELY "approve" this PR. But I'm not happy about it, and will be submitting a bug report.

2019-05-14 20:16 UTC, murphyad approved these changes

2019-05-15 20:55 UTC, merged